apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: model:latest
          imagePullPolicy: Never
          workingDir: /app
          envFrom:
            - configMapRef:
                name: shared-configmap
          volumeMounts:
            - name: model-weights
              mountPath: /app/model
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: model-logs
        - name: model-weights
          persistentVolumeClaim:
            claimName: model-weights
