apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov8_model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov8_model
  template:
    metadata:
      labels:
        app: yolov8_model
    spec:
      containers:
      - name: yolov8_model
        image: yolov8_model:latest
        volumeMounts:
        - name: models
          mountPath: /app/model
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc
