apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-weights
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
